### ISSUE TITLE
Minification on publish is broken

### ISSUE THREAD

**Issue by joelrich** [Adobe-Marketing-Cloud/aem-sample-we-retail#101]
The following line in jQuery is causing the issue because of ```.throws```:
```if ( conv && s.throws ) {```
Since we cannot use GCC as the default minifier (see #97) and it does not seem to be possible to enable GCC only for certain files, I would propose to to replace ```s.throws``` with ```s['throws']```.

**Comment by joelrich** [comment]
Pull request: https://github.com/Adobe-Marketing-Cloud/aem-sample-we-retail/pull/102
The problem with this solution is that it will break whenever jQuery is updated. Unfortunately, I don't see a better solution.

**Comment by justinedelson** [comment]
should be left open until #103 (or some other fix) is merged.
