### ISSUE TITLE
Secondary menu overlay issue, over form elements and icons

### ISSUE THREAD

**Issue by coatpont** [Adobe-Marketing-Cloud/aem-sample-we-retail#109]
The secondary-level navigation menu isn't taking z-index precedence over some page elements like form controls or icons, e.g. 

http://ot1slu028.corp.adobe.com:4503/content/we-retail/community/en/catalog.html
http://ot1slu028.corp.adobe.com:4503/content/we-retail/community/en/calendar.html

**Comment by raducotescu** [comment]
This seems to be a product related defect regarding some SoCo components that use an explicit z-index value.

**Comment by badvision** [comment]
Is this defect still valid?  If not, can we close this out?

**Comment by coatpont** [comment]
has been fixed 1 year ago I think
