### ISSUE TITLE
Integration test launcher dependencies kill AEM instance

### ISSUE THREAD

**Issue by ottonagy** [Adobe-Marketing-Cloud/aem-sample-we-retail#117]
**Environment**
- AEM version : Adobe Experience Manager (6.2.0)
- Java version : 1.8.0_101
- Operating system : Windows 7

**Steps to reproduce**
- Start a fresh AEM 6.2 author instance by running `java -jar cq-author-p4502.jar` in a cmd shell
- Check out the latest master branch (at the time of writing https://github.com/Adobe-Marketing-Cloud/aem-sample-we-retail/commit/fc31e133e38fe3b8f70d6511c6b443b879a7a4a4)
- Launch the integration tests by executing `mvn clean integration-test -PintegrationTests` in a cmd shell
- Integration tests will fail (but this is not the main issue here)
- Restart your AEM instance

After the last step AEM fails to start normally as most of the bundles are unable to start.

**Root cause**
The integration test launcher module defines and installs the following dependencies :

```
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient-osgi</artifactId>
            <version>4.1.2</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpcore-osgi</artifactId>
            <version>4.1.2</version>
            <scope>provided</scope>
        </dependency>
```

but these are already provided by AEM 6.2 OOTB but with different versions (4.3.4 and 4.3.2, respectively) so basically by **launching the integration tests those bundles are downgraded** (as AEM doesn't support multiple versions of the same dependency)

**Comment by ottonagy** [comment]
The relevant log records are
[issue-117-stderr.log.txt](https://github.com/Adobe-Marketing-Cloud/aem-sample-we-retail/files/516155/issue-117-stderr.log.txt)

**Comment by ottonagy** [comment]
I suppose this issue is present in the already released `1.0.0` version, too.

**Comment by bpauli** [comment]
@ottonagy Thanks for reporting this issue. We will have a look to it.

**Comment by bpauli** [comment]
The integration test launcher was removed in the latest release.
