### ISSUE TITLE
issue with Master branch 

### ISSUE THREAD

**Issue by subratkd** [Adobe-Marketing-Cloud/aem-sample-we-retail#122]
Hello Team,
The master branch is giving me the below error and none of the versions is working foe me . please help.

 Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project we.retail.core: Compilation failure: Compilation failure:
[ERROR] error reading C:\Users\dashs\.m2\repository\com\adobe\aem\uber-jar\6.2.0\uber-jar-6.2.0-apis.jar; error in opening zip file
[ERROR] error reading C:\Users\dashs\.m2\repository\com\adobe\aem\uber-jar\6.2.0\uber-jar-6.2.0-apis.jar; error in opening zip file
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/util/WeRetailHelper.java:[3,26] package com.day.cq.wcm.api does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/util/WeRetailHelper.java:[4,26] package com.day.cq.wcm.api does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/util/WeRetailHelper.java:[5,37] package org.apache.sling.api.resource does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/util/WeRetailHelper.java:[6,37] package org.apache.sling.api.resource does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/util/WeRetailHelper.java:[45,41] cannot find symbol
[ERROR] symbol:   class Resource
[ERROR] location: class we.retail.core.util.WeRetailHelper
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/util/WeRetailHelper.java:[45,66] cannot find symbol
[ERROR] symbol:   class Page
[ERROR] location: class we.retail.core.util.WeRetailHelper
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/util/WeRetailHelper.java:[68,45] cannot find symbol
[ERROR] symbol:   class Page
[ERROR] location: class we.retail.core.util.WeRetailHelper
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/util/WeRetailHelper.java:[86,41] cannot find symbol
[ERROR] symbol:   class Page
[ERROR] location: class we.retail.core.util.WeRetailHelper
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/WeRetailCommerceSessionImpl.java:[3,33] package com.adobe.cq.commerce.api does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/WeRetailCommerceSessionImpl.java:[4,33] package com.adobe.cq.commerce.api does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/WeRetailCommerceSessionImpl.java:[5,33] package com.adobe.cq.commerce.api does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/WeRetailCommerceSessionImpl.java:[6,36] package com.adobe.cq.commerce.common does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/WeRetailCommerceSessionImpl.java:[7,36] package com.adobe.cq.commerce.common does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/WeRetailCommerceSessionImpl.java:[8,23] package com.day.cq.i18n does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/WeRetailCommerceSessionImpl.java:[9,34] package org.apache.jackrabbit.util does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/WeRetailCommerceSessionImpl.java:[10,28] package org.apache.sling.api does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/WeRetailCommerceSessionImpl.java:[11,28] package org.apache.sling.api does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/WeRetailCommerceSessionImpl.java:[12,37] package org.apache.sling.api.resource does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/WeRetailCommerceSessionImpl.java:[25,50] cannot find symbol
[ERROR] symbol: class AbstractJcrCommerceSession
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/WeRetailCommerceSessionImpl.java:[27,40] cannot find symbol
[ERROR] symbol:   class AbstractJcrCommerceService
[ERROR] location: class we.retail.core.WeRetailCommerceSessionImpl
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/WeRetailCommerceSessionImpl.java:[28,35] cannot find symbol
[ERROR] symbol:   class SlingHttpServletRequest
[ERROR] location: class we.retail.core.WeRetailCommerceSessionImpl
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/WeRetailCommerceSessionImpl.java:[29,35] cannot find symbol
[ERROR] symbol:   class SlingHttpServletResponse
[ERROR] location: class we.retail.core.WeRetailCommerceSessionImpl
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/WeRetailCommerceSessionImpl.java:[30,35] cannot find symbol
[ERROR] symbol:   class Resource
[ERROR] location: class we.retail.core.WeRetailCommerceSessionImpl
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/WeRetailCommerceSessionImpl.java:[30,61] cannot find symbol
[ERROR] symbol:   class CommerceException
[ERROR] location: class we.retail.core.WeRetailCommerceSessionImpl
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/WeRetailCommerceSessionImpl.java:[56,85] cannot find symbol
[ERROR] symbol:   class CommerceException
[ERROR] location: class we.retail.core.WeRetailCommerceSessionImpl
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/WeRetailCommerceSessionImpl.java:[65,69] cannot find symbol
[ERROR] symbol:   class CommerceException
[ERROR] location: class we.retail.core.WeRetailCommerceSessionImpl
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/WeRetailCommerceSessionImpl.java:[80,60] cannot find symbol
[ERROR] symbol:   class CommerceException
[ERROR] location: class we.retail.core.WeRetailCommerceSessionImpl
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/Article.java:[10,28] package com.adobe.cq.dam.cfm does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/Article.java:[11,28] package com.adobe.cq.dam.cfm does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/Article.java:[12,28] package com.adobe.cq.dam.cfm does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/Article.java:[13,26] package com.day.cq.dam.api does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/Article.java:[14,47] package org.apache.jackrabbit.api.security.user does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/Article.java:[15,37] package org.apache.sling.api.resource does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/Article.java:[16,37] package org.apache.sling.api.resource does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/Article.java:[17,37] package org.apache.sling.api.resource does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/Article.java:[18,43] package org.apache.sling.models.annotations does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/Article.java:[19,43] package org.apache.sling.models.annotations does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/Article.java:[20,60] package org.apache.sling.models.annotations.injectorspecific does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/Article.java:[21,60] package org.apache.sling.models.annotations.injectorspecific does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/Article.java:[25,30] package com.day.cq.commons.jcr does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/Article.java:[26,26] package com.day.cq.tagging does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/Article.java:[27,26] package com.day.cq.tagging does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/Article.java:[32,2] cannot find symbol
[ERROR] symbol: class Model
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/Article.java:[48,13] cannot find symbol
[ERROR] symbol:   class ResourceResolver
[ERROR] location: class we.retail.core.Article
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/Article.java:[56,15] cannot find symbol
[ERROR] symbol:   class ContentFragment
[ERROR] location: class we.retail.core.Article
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/Article.java:[58,12] cannot find symbol
[ERROR] symbol:   class Resource
[ERROR] location: class we.retail.core.Article
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/Article.java:[60,20] cannot find symbol
[ERROR] symbol:   class Resource
[ERROR] location: class we.retail.core.Article
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/Article.java:[87,17] cannot find symbol
[ERROR] symbol:   class Tag
[ERROR] location: class we.retail.core.Article
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/Profile.java:[10,37] package org.apache.sling.api.resource does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/Profile.java:[11,43] package org.apache.sling.models.annotations does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/Profile.java:[12,43] package org.apache.sling.models.annotations does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/Profile.java:[17,2] cannot find symbol
[ERROR] symbol: class Model
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/Profile.java:[38,12] cannot find symbol
[ERROR] symbol:   class Resource
[ERROR] location: class we.retail.core.Profile
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/productrelationships/SimilarToCurrentRelationshipsProvider.java:[4,33] package com.adobe.cq.commerce.api does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/productrelationships/SimilarToCurrentRelationshipsProvider.java:[5,33] package com.adobe.cq.commerce.api does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/productrelationships/SimilarToCurrentRelationshipsProvider.java:[6,33] package com.adobe.cq.commerce.api does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/productrelationships/SimilarToCurrentRelationshipsProvider.java:[7,33] package com.adobe.cq.commerce.api does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/productrelationships/SimilarToCurrentRelationshipsProvider.java:[8,33] package com.adobe.cq.commerce.api does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/productrelationships/SimilarToCurrentRelationshipsProvider.java:[9,33] package com.adobe.cq.commerce.api does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/productrelationships/SimilarToCurrentRelationshipsProvider.java:[10,34] package com.day.cq.commons.inherit does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/productrelationships/SimilarToCurrentRelationshipsProvider.java:[11,34] package com.day.cq.commons.inherit does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/productrelationships/SimilarToCurrentRelationshipsProvider.java:[12,26] package com.day.cq.wcm.api does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/productrelationships/SimilarToCurrentRelationshipsProvider.java:[19,28] package org.apache.sling.api does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/productrelationships/SimilarToCurrentRelationshipsProvider.java:[20,37] package org.apache.sling.api.resource does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/productrelationships/SimilarToCurrentRelationshipsProvider.java:[21,37] package org.apache.sling.commons.osgi does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/productrelationships/SimilarToCurrentRelationshipsProvider.java:[48,63] cannot find symbol
[ERROR] symbol: class ProductRelationshipsProvider
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/productrelationships/SimilarToCurrentRelationshipsProvider.java:[80,55] cannot find symbol
[ERROR] symbol:   class SlingHttpServletRequest
[ERROR] location: class we.retail.core.productrelationships.SimilarToCurrentRelationshipsProvider
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/productrelationships/SimilarToCurrentRelationshipsProvider.java:[80,88] cannot find symbol
[ERROR] symbol:   class CommerceSession
[ERROR] location: class we.retail.core.productrelationships.SimilarToCurrentRelationshipsProvider
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/productrelationships/SimilarToCurrentRelationshipsProvider.java:[80,113] cannot find symbol
[ERROR] symbol:   class Page
[ERROR] location: class we.retail.core.productrelationships.SimilarToCurrentRelationshipsProvider
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/productrelationships/SimilarToCurrentRelationshipsProvider.java:[81,55] cannot find symbol
[ERROR] symbol:   class Product
[ERROR] location: class we.retail.core.productrelationships.SimilarToCurrentRelationshipsProvider
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/productrelationships/SimilarToCurrentRelationshipsProvider.java:[80,17] cannot find symbol
[ERROR] symbol:   class ProductRelationship
[ERROR] location: class we.retail.core.productrelationships.SimilarToCurrentRelationshipsProvider
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/productrelationships/SimilarToCurrentRelationshipsProvider.java:[81,86] cannot find symbol
[ERROR] symbol:   class CommerceException
[ERROR] location: class we.retail.core.productrelationships.SimilarToCurrentRelationshipsProvider
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/components/impl/ArticleImageServlet.java:[18,26] package com.day.cq.commons does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/components/impl/ArticleImageServlet.java:[19,30] package com.day.cq.commons.jcr does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/components/impl/ArticleImageServlet.java:[20,26] package com.day.cq.dam.api does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/components/impl/ArticleImageServlet.java:[21,26] package com.day.cq.dam.api does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/components/impl/ArticleImageServlet.java:[22,26] package com.day.cq.dam.api does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/components/impl/ArticleImageServlet.java:[23,30] package com.day.cq.wcm.commons does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/components/impl/ArticleImageServlet.java:[24,33] package com.day.cq.wcm.foundation does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/components/impl/ArticleImageServlet.java:[25,21] package com.day.image does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/components/impl/ArticleImageServlet.java:[27,28] package org.apache.sling.api does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/components/impl/ArticleImageServlet.java:[28,28] package org.apache.sling.api does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/components/impl/ArticleImageServlet.java:[29,37] package org.apache.sling.api.resource does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/components/impl/ArticleImageServlet.java:[36,42] cannot find symbol
[ERROR] symbol: class AbstractImageServlet
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/components/impl/ArticleImageServlet.java:[38,26] cannot find symbol
[ERROR] symbol:   class RenditionPicker
[ERROR] location: class we.retail.core.components.impl.ArticleImageServlet
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/components/impl/ArticleImageServlet.java:[44,33] cannot find symbol
[ERROR] symbol:   class ImageContext
[ERROR] location: class we.retail.core.components.impl.ArticleImageServlet
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/components/impl/ArticleImageServlet.java:[44,15] cannot find symbol
[ERROR] symbol:   class Layer
[ERROR] location: class we.retail.core.components.impl.ArticleImageServlet
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/components/impl/ArticleImageServlet.java:[78,31] cannot find symbol
[ERROR] symbol:   class SlingHttpServletRequest
[ERROR] location: class we.retail.core.components.impl.ArticleImageServlet
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/components/impl/ArticleImageServlet.java:[78,64] cannot find symbol
[ERROR] symbol:   class SlingHttpServletResponse
[ERROR] location: class we.retail.core.components.impl.ArticleImageServlet
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/components/impl/ArticleImageServlet.java:[78,99] cannot find symbol
[ERROR] symbol:   class ImageContext
[ERROR] location: class we.retail.core.components.impl.ArticleImageServlet
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/components/impl/ArticleImageServlet.java:[78,121] cannot find symbol
[ERROR] symbol:   class Layer
[ERROR] location: class we.retail.core.components.impl.ArticleImageServlet
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/WeRetailProductImpl.java:[3,36] package com.adobe.cq.commerce.common does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/WeRetailProductImpl.java:[4,26] package com.day.cq.wcm.api does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/WeRetailProductImpl.java:[5,26] package com.day.cq.wcm.api does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/WeRetailProductImpl.java:[6,37] package org.apache.sling.api.resource does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/WeRetailProductImpl.java:[7,37] package org.apache.sling.api.resource does not exist
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/WeRetailProductImpl.java:[13,42] cannot find symbol
[ERROR] symbol: class AbstractJcrProduct
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/WeRetailProductImpl.java:[17,21] cannot find symbol
[ERROR] symbol:   class ResourceResolver
[ERROR] location: class we.retail.core.WeRetailProductImpl
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/WeRetailProductImpl.java:[18,21] cannot find symbol
[ERROR] symbol:   class PageManager
[ERROR] location: class we.retail.core.WeRetailProductImpl
[ERROR] /C:/AEM Code/aem-sample-we-retail-master/core/src/main/java/we/retail/core/WeRetailProductImpl.java:[19,21] cannot find symbol
[ERROR] symbol:   class Page
[ERROR] location: class we.retail.core.WeRetailProductImpl
[ERROR] -> [Help 1]

**Comment by bpauli** [comment]
@subratkd It looks like that your locale maven repository has corrupt download of the uber-jar. Can you please try to delete the folder C:\Users\dashs.m2\repository\com\adobe\aem\uber-jar\6.2.0 on your machine? The `mvn clean install` should now work.
Thanks!
