### ISSUE TITLE
Test Cases Expecting USD prices fail if project built on non-US machines

### ISSUE THREAD

**Issue by ichirital** [Adobe-Marketing-Cloud/aem-sample-we-retail#123]
Results :

Failed tests:
  OrderModelTest.testOrderEntries:102 expected:<[$]24.00> but was:<[£]24.00>
  ShoppingCartModelTest.testCartEntries:78 expected:<[$]24.00> but was:<[£]24.00>
  ShoppingCartModelTest.testCartPrices:92 expected:<[$]167.00> but was:<[£]167.00>

Tests run: 11, Failures: 3, Errors: 0, Skipped: 0

OS:
ProductName:	Mac OS X
ProductVersion:	10.12.4
BuildVersion:	16E195

Environment Vars:
LANG=en_GB.UTF-8

Java:
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

**Comment by bpauli** [comment]
@ichirital Thank you for reporting this issue! 
The locale in the MockCommerceSession is now set to en_US independently from the machines locale.
