### ISSUE TITLE
Provide the parent pom in the Adobe Repo as well

### ISSUE THREAD

**Issue by kwin** [Adobe-Marketing-Cloud/aem-sample-we-retail#124]
Currently only the modules are available in https://repo.adobe.com/nexus/content/groups/public/com/adobe/cq/sample/ but not the parent `com.adobe.cq.sample:we.retail:2.0.2`. Can you publish the latter as well?

**Comment by bpauli** [comment]
The parent `com.adobe.cq.sample:we.retail:2.0.2` has been published on repo.adobe.com as well. Thanks for the hands up.
