### ISSUE TITLE
Missing "Cache-Control: no-store" header for dynamically generated resources

### ISSUE THREAD

**Issue by mkolmhuber** [Adobe-Marketing-Cloud/aem-sample-we-retail#125]
All "contexthub.commerce.*.json" references pretend to refer to static resources but in real life they are dynamically generated.

Consequently, the "Cache-Control: no-store" response header must be set in every response to a "contexthub.commerce.*.json" request to prevent the caching of a dynamically generated resource.

**Comment by kwin** [comment]
Please also make sure then that those resources are never cached in the dispatcher either with "Dispatcher: no-cache" then as well (https://helpx.adobe.com/experience-manager/kb/DispatcherNoCache.html)

**Comment by mhaack** [comment]
The "contexthub.commerce.*.json" calls are triggered by ContextHub. This is not an we.retail issue, please open a AEM Support ticket for that, if still relevant.
