### ISSUE TITLE
Remove RAT check for end user

### ISSUE THREAD

**Issue by sammykumar** [Adobe-Marketing-Cloud/aem-sample-we-retail#127]
Building We-Retail on the master branch fails due to unapproved licenses found during rat check

>   it.launcher/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
>   it.launcher/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
>   it.launcher/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/createdFiles.lst
>   it.launcher/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
>   it.launcher/we.retail.it.launcher.iml
>   it.tests/target/classes/META-INF/MANIFEST.MF
>   it.tests/we.retail.it.tests.iml

As the end user, the only way to bypass this is to run with ```-Drat.skip```

I'd like to help fix this but, I'm not sure what the best way about this is. Should I submit a PR removing rat check complete or exclude the files that are being flagged by rat check?

**Comment by raducotescu** [comment]
@sammykumar, there's no `it.launcher` module on the `master` branch for quite some time: 86c4f15. I guess your clone still has that folder for some reason. Please delete it and try to rebuild.

**Comment by sammykumar** [comment]
Thanks @raducotescu. Strange that I still had it.
