### ISSUE TITLE
Hybris connector with We.Retail site is not working

### ISSUE THREAD

**Issue by kapilmalik84** [Adobe-Marketing-Cloud/aem-sample-we-retail#128]
Hi All,
I am trying to do the following and could not get this working:
1. Created Fresh AEM 6.2 instance and installed we.retail package.
2. Installed cq-6.2.100.zip package mentioned on the AEM hybris  integration page.
3. Configured the hybrid server URL and catalog.
4. Imported the hybris  catalog to AEM and the products are visible under etc/commerce/products/catalog_name/
5. Created a new product page in we.retail site and using product component
6. Product Price, description,images, cart, checkout and many more functionalies are not loaded on the page.
However if I use geometrixx-Outdoors site everything works fine.
Can some one help?

**Comment by mhaack** [comment]
@kapilmalik84 Can you provide more details?

- Which commerce provider did you configure for the we.retail site. 
- Any messages in the error.log?

**Comment by mhaack** [comment]
No response since one week, closing this issue. Please reopen if you have further questions.
