### ISSUE TITLE
Multi Language Products

### ISSUE THREAD

**Issue by cduque89** [Adobe-Marketing-Cloud/aem-sample-we-retail#129]
Hi all.

I can I have a product in more than one language? 

I am using we.retail with AEM 6.2 and in the CRX it is possible to see that some products have some properties defined for different languages.

For example product: `/etc/commerce/products/we-retail/eq/hiking/eqsmcz/eqsmcz.1` as title and title.ga as in the image below:

![image](https://user-images.githubusercontent.com/22081254/27405663-636ce5cc-56ca-11e7-9ced-2284aa2629d4.png)

When we go to edit the product details I cannot find any way to change that title.ga propertie. I really needed this to be possible for my current implementation.

![image](https://user-images.githubusercontent.com/22081254/27405747-bcc349d6-56ca-11e7-8d7b-6972c2f6efb4.png)

Can someone help with this issue?

**Comment by mhaack** [comment]
Yes you can have different languages for product data. The `eqsmcz` example product you referenced above shows how to store the translations.

To make them visible in to product editor UI you need to adapt the scaffolding definition for product data. For we.retail on AEM 6.2 this is `/etc/scaffolding/we-retail/products`, this config defines which properties are visible via the UI.
