### ISSUE TITLE
Make we-retail compatible with the most recent Core WCM Components

### ISSUE THREAD

**Issue by kwin** [Adobe-Marketing-Cloud/aem-sample-we-retail#131]
Due to a major package version increase (https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/issues/29) in com.adobe.cq.wcm.core.components.models the most recent version of the Core WCM Components is no longer compatible with we retail. Please upgrade the dependency therefore to the most recent release or manually widen the import-range to also cover the new version of wcm core components.

**Comment by raducotescu** [comment]
Fixed in 09d843f8dbee6b650166fc80df437b67ce2fe8f0.
