### ISSUE TITLE
Unable to build from scratch: Too many files with unapproved license error

### ISSUE THREAD

**Issue by badvision** [Adobe-Marketing-Cloud/aem-sample-we-retail#137]
I was able to bypass this by passing a disable flag to Apache Rat (via -Drat.skip=true), but is it possible that maybe there's a newer version of Apache Rat that won't throw this error?

**Comment by vladbailescu** [comment]
@badvision, you might have some leftover folders/files from a previous version. I don't see thins issue with a new repo clone.

**Comment by bpauli** [comment]
@badvision I'm closing this issue as it's not reproducible on my build. If the issue still occurs please provide the generated `rat.txt` file. Thanks!
