### ISSUE TITLE
Default dispatcher config doesnt work with We.retail

### ISSUE THREAD

**Issue by timdonovanuk** [Adobe-Marketing-Cloud/aem-sample-we-retail#138]
Due to clientlib proxing, css and js are served from /etc.clientlibs and this is not enabled or documented anywhere (AFAIK) in any exemplar dispatcher.any files - so these resources will be blocked by default.

/filter 
 /0029 { /type "allow" /url "/etc.clientlibs*"    }

or something like that.

**Comment by vladbailescu** [comment]
@timdonovanuk This is covered by documentation starting with AEM 6.3: https://helpx.adobe.com/experience-manager/6-3/sites/developing/using/clientlibs.html#main-pars_title_8ced
