### ISSUE TITLE
CategoryTeaser invalid href

### ISSUE THREAD

**Issue by knennigtri** [Adobe-Marketing-Cloud/aem-sample-we-retail#141]
When translating a page that has a categoryTeaser component configured with a href in the same language branch and then the page is translated, but the href location is not, it results in an invalid link on the component which creates: 
`<img src="/libs/cq/linkchecker/resources/linkcheck_o.gif" alt="invalid link: /content/we-retail/language-masters/es/products/women/shirts.html" title="invalid link: /content/we-retail/language-masters/es/products/women/shirts.html" border="0">`
Which shows a huge image across the entire screen.

This can be easily replicated on a fresh instance of AEM. Translate the language-masters/en/women to language-masters/es/women. This will result in the error (large image overlaying entire page).

The easiest fix is simply to update the CategoryTeaser.java file with a better default value. Update line 47 to:
`buttonLinkTo = properties.get(PROP_BUTTON_LINK_TO, "#");`
This allows the default href to be "#" rather than "", fixing the issue.

**Comment by gabrielwalt** [comment]
I'd expect this to be solved with the fixes that we made to the broken link image and we also created a new teaser component. I'll close this issue for now, but please reopen in case the problem reappears.
