### ISSUE TITLE
OrderHistoryModelTest may fail based on timezone

### ISSUE THREAD

**Issue by josephrignanese** [Adobe-Marketing-Cloud/aem-sample-we-retail#143]
When performing a build the OrderHistoryModelTest assertions can fail dependant on the the user's timezone
[mvn-error.log](https://github.com/Adobe-Marketing-Cloud/aem-sample-we-retail/files/1526313/mvn-error.log)

**Comment by josephrignanese** [comment]
I'll put a together a fix tomorrow

**Comment by vladbailescu** [comment]
Closed via #144
