### ISSUE TITLE
autoInstallPackage does not deploy bundle

### ISSUE THREAD

**Issue by joaotab** [Adobe-Marketing-Cloud/aem-sample-we-retail#146]
Running mvn clean install -PautoInstallPackage on a clean AEM 6.3 instance (nosamplecontent) doesn't seem to deploy the core bundle.

Is this expected behaviour i.e. to run -PautoInstallBundle separately?

**Comment by vladbailescu** [comment]
You can either install everything using `mvn clean install -PautoInstallSinglePackage` or you can install the bundle and content package separately. These options are documented at https://github.com/Adobe-Marketing-Cloud/aem-sample-we-retail#how-to-build

**Comment by joaotab** [comment]
Thank you for clarifying!

It is a bit confusing coming from the Adobe maven archetype where autoInstallPackage installs both the ui.apps package and the core bundle. Also the doc states "you can build and package the whole project and deploy into AEM with [...] -PautoInstallPackage" which is misleading.

In any case, if it's the expected behaviour, I'll close it.
