### ISSUE TITLE
We.Retail does not support core components v2

### ISSUE THREAD

**Issue by dmitry-cherkas** [Adobe-Marketing-Cloud/aem-sample-we-retail#147]
After following https://helpx.adobe.com/experience-manager/kt/sites/using/getting-started-wknd-tutorial-develop.html We.Retail fails to resolve dependencies.
Steps to reproduce:
1. Install AEM 6.3 + SP1 + [FP20593](https://www.adobeaemcloud.com/content/marketplace/marketplaceProxy.html?packagePath=/content/companies/public/adobe/packages/cq630/featurepack/cq-6.3.0-featurepack-20593)
2. Check http://localhost:4502/system/console/bundles for bundles status

**Expected:** All bundles are Active/Fragment
**Actual:** com.adobe.cq.sample.we.retail.core is "Installed"
![image](https://user-images.githubusercontent.com/3441528/36506587-21f98a50-1768-11e8-9d05-d412d986469d.png)

**Comment by bpauli** [comment]
fixed in https://github.com/Adobe-Marketing-Cloud/aem-sample-we-retail/commit/c509c0c68f8941fad8d69eff237ab6b9b51fbdd3
