### ISSUE TITLE
Thread Safety issue in CountriesFormOptionsDataSource

### ISSUE THREAD

**Issue by justinedelson** [Adobe-Marketing-Cloud/aem-sample-we-retail#148]
The class CountriesFormOptionsDataSource uses an instance variable to store the `I18n` object. At scale, this will result in the wrong resource bundle being used single multiple concurrent invocations of this servlet will overwrite this object. Instead of an instance variable, it should be a local variable passed method to method.

**Comment by bpauli** [comment]
@justinedelson Thank you for the hands up. We will fix this issue in the upcoming release. (4237823)

**Comment by bpauli** [comment]
fixed in https://github.com/Adobe-Marketing-Cloud/aem-sample-we-retail/commit/c509c0c68f8941fad8d69eff237ab6b9b51fbdd3
