### ISSUE TITLE
Test fail at  Unparseable date: "Mon Dec 12 2016 16:42:15 GMT+0100"

### ISSUE THREAD

**Issue by matrut** [Adobe-Marketing-Cloud/aem-sample-we-retail#149]
Error while running mvn clean install due the tests failure at we.retail.core.model.OrderHistoryModelTest - Unparseable date: "Mon Dec 12 2016 16:42:15 GMT+0100"

**Comment by devinyan** [comment]
yeah , i met the same issue. I just commented the exception java code(Line 103 and 113) in OrderHistoryModelTest.java.

**Comment by AlessioG** [comment]
I think you should change the line51 in OrderHistoryModelTest to add the locale and delete the Z reference.

private SimpleDateFormat dateParser = new SimpleDateFormat("EEE MMM dd yyyy HH:mm:ss 'GMT'", Locale.US);

**Comment by bpauli** [comment]
@matrut, @devinyan  Thanks for the hands up and @AlessioG for providing the fix.
