### ISSUE TITLE
We.Retail pages do not load correctly inside the Target Visual Experience Composer (VEC)

### ISSUE THREAD

**Issue by ittaibaratz** [Adobe-Marketing-Cloud/aem-sample-we-retail#151]
When loading a we.retail webpage inside Adobe Target Visual Experience Composer (VEC), the page does not render correctly as shown below:

![image](https://user-images.githubusercontent.com/1454683/37871539-cf675664-2fa4-11e8-957f-d3cc847478aa.png)

The page footer is located right below the header, instead of the bottom of the page. 
This is because the we.retail expects the body element to have relative position, however inside the VEC , Adobe Target overrides the body position and makes it static:

![image](https://user-images.githubusercontent.com/1454683/37871559-434ff3f6-2fa5-11e8-8809-44e194a69813.png)

I was able to solve this on my local AEM instance by removing the bottom value from **.footer .we-Footer**
(https://github.com/Adobe-Marketing-Cloud/aem-sample-we-retail/blob/master/ui.apps/src/main/content/jcr_root/apps/weretail/components/structure/footer/clientlibs/less/footer.less)

I don't think the bottom value is necessary as the footer will flow to the bottom without it. Please check. This fix is required for demoing We.Retail content inside Adobe Target.

cc @keepthebyte , @martinbuergi , @gabrielwalt @gknobloch @bpauli

**Comment by gabrielwalt** [comment]
I agree, we could have the footer positioned statically.

**Comment by jckautzmann** [comment]
(CQ-4263821)

**Comment by jckautzmann** [comment]
This issue has been fixed and will be available with the 4.0.0 release of We.Retail
