### ISSUE TITLE
Package matrix

### ISSUE THREAD

**Issue by mhaack** [Adobe-Marketing-Cloud/aem-sample-we-retail#153]
It would be nice if the readme can get some overview table which combination of packages (we.retail + commons + core components) can be installed on AEM 6.3, 6.4.

**Comment by gknobloch** [comment]
Looks like https://helpx.adobe.com/experience-manager/core-components/using/versions.html should be linked from the `README`

**Comment by mhaack** [comment]
Also core.wcm.components.extension and we.retail.commons.content should be in such a matrix.

**Comment by jckautzmann** [comment]
(CQ-4263739)

**Comment by jckautzmann** [comment]
This issue has been fixed on the private We.Retail repo.

**Comment by vladbailescu** [comment]
This is now fixed at https://github.com/Adobe-Marketing-Cloud/aem-sample-we-retail#release-history-and-system-requirements
