### ISSUE TITLE
Social Links

### ISSUE THREAD

**Issue by luckyluke80** [Adobe-Marketing-Cloud/aem-sample-we-retail#155]
## Feature Request

In the preview/documentation, the social links are visible in the footer of the welcome page. But so far I was not able to find a component, where I can configure the social links. (Facebook, Twitter, ...)

Please provide a dialog or include a component, where the social links are configurable.

[we retail documentation](https://helpx.adobe.com/experience-manager/6-4/sites/developing/using/we-retail.html#Appendix)

**Comment by bpauli** [comment]
@luckyluke80, Thank you for the pointer. The documentation isn't up to date in this case. With AEM 6.4 there is a dedicate Social Media Component which can be added to the layout container. But first the social media needs to be enabled inside of the page properties dialog.
