### ISSUE TITLE
Carousel and Tabs component

### ISSUE THREAD

**Issue by JasonZhang1978** [Adobe-Marketing-Cloud/aem-sample-we-retail#157]
I installed core 2.2.0 on AEM 6.4.2.0. I create proxy component in my project and a demo page to pull in tabs and carousel component. on config dialog, nothing happened when i click add button. in the console i get the below error. any idea? Thanks

Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at core.js:24418
    at Array.forEach (<anonymous>)
    at filterComponent (core.js:24404)
    at core.js:24508
    at coralui3.js:4889

**Comment by jckautzmann** [comment]
Did you enable the editing functionality as described at:
https://github.com/adobe/aem-core-wcm-components/tree/master/content/src/content/jcr_root/apps/core/wcm/components/carousel/v1/carousel#enabling-carousel-editing-functionality
?
