### ISSUE TITLE
Question: XF body.html contains <!DOCTYPE html>

### ISSUE THREAD

**Issue by JasonUSC** [Adobe-Marketing-Cloud/aem-sample-we-retail#158]
We noticed that the body.html We.Retail code contains a <!DOCTYPE html> declaration at the top of the template, even though body.html typically gets included inside a page that already has this declaration. Is this intentional or an error?  /apps/weretail/components/structure/xfpage/body.html

The body.html file in libs/cq is completely empty so we have doubts that it serves a purpose. /libs/cq/experience-fragments/components/experiencefragment/body.html

**Comment by andreeadracea** [comment]
@JasonUSC, indeed this is an error. 
I created an internal issue for solving this error (CQ-4259204)

**Comment by andreeadracea** [comment]
This problem got solved in master branch
