### ISSUE TITLE
Wrong blueprint configuration and MSM "Create Site" functionality

### ISSUE THREAD

**Issue by YuriyShestakov** [Adobe-Marketing-Cloud/aem-sample-we-retail#160]
If we use "Create Site" functionality as it described here: https://helpx.adobe.com/experience-manager/6-4/sites/administering/using/msm.html#MSMfromtheUI to create new region copy and automatically rollout all chapters (all children), we take the following steps:

1. Button 'Create -> Site' in MSM
2. Choosing blueprint 'We.Retail English'

On the next page of the wizard along with the list of acceptable languages, you can see Initial Chapters selection component, which shows us such chapters as "Arctic Surfing In Lofoten (arctic-surfing-in-lofoten)",  "48 hours of Wilderness (hours-of-wilderness)" etc., which are absolutely wrong, because they are not chapters, but children pages of the section "Experience". The chapters actually should contain "Experience", "Men", "Women" and other child pages of the "en" page.

According to this manual: https://helpx.adobe.com/experience-manager/6-4/sites/administering/using/msm-livecopy.html#ManagingBlueprintConfigurations
Blueprint configuration page should contain: 

- a root page
- immediate child pages that are language branches of a website
- language branches' child pages which are represented as chapters that you can include in the live copy.

So, cause our blueprint configuration (you can see it here: http://localhost:4502/libs/wcm/msm/gui/content/blueprintconfig.html or in sources: https://github.com/Adobe-Marketing-Cloud/aem-sample-we-retail/blob/master/ui.apps/src/main/content/jcr_root/apps/msm/we-retail/blueprintconfigs/weretail-english/.content.xml) refers as a source to the page "/content/we-retail/language-masters/en" it seems like AEM is working perfectly - it supposes that "Experience" is a language page and shows all its children as chapters, and the problem is in our blueprint configuration. Looks like all these configurations "We.Retail English", "We.Retail French", "We.Retail German", "We.Retail Italian", "We.Retail Spanish" that we have in our sources are absolutely unuseful and should be removed. We should have just one Blueprint configuration which should refer to page /content/we-retail/language-masters as a source.

I've created such configuration for testing purposes and tried to create a new site using it, and it looks like working as needed.

**Comment by YuriyShestakov** [comment]
Also, I've created Live Copy site using this default Blueprint configuration "We.Retail English", and they have gotten both the same Live Sync Config master page property (cq:LiveSyncConfig/cq:master) and its value is /content/we-retail/language-masters/en. Which is wrong, because it's clear that it can cause rollout errors. And no chapters were created under a new language root node.

**Comment by andreeadracea** [comment]
@YuriyShestakov, thank you for bringing up this issue. This is a problem from the product and not from We-retail. 

I've created an internal issue for it.
(CQ-4259713)

**Comment by YuriyShestakov** [comment]
It's absolutely not a problem with the product. My _last comment_ might be a problem of AEM, but not the issue by itself. 
The problem is in the **content** section of We-Retail, where the file [.../msm/we-retail/blueprintconfigs/weretail-english/.content.xml](https://github.com/Adobe-Marketing-Cloud/aem-sample-we-retail/blob/master/ui.apps/src/main/content/jcr_root/apps/msm/we-retail/blueprintconfigs/weretail-english/.content.xml) does not correspond to the idea of blueprints described in current AEM documentation and does not follow the documentation at all!

**Comment by andreeadracea** [comment]
@YuriyShestakov, I checked with the team who created blueprint functionality to be sure is a we-retail problem and not a wrong documentation, and indeed is a wrong configuration for we-retail blueprint. 
We will solve this problem in the internal issue I've created.

**Comment by YuriyShestakov** [comment]
@andreeadracea Ok, thank you.

**Comment by andreeadracea** [comment]
This problem got solved in master branch
