### ISSUE TITLE
[List Component] Shows list images in Content Tree

### ISSUE THREAD

**Issue by godanny86** [Adobe-Marketing-Cloud/aem-sample-we-retail#161]
In AEM 6.5 the list component is added to several pages (/content/we-retail/language-masters/en/women.html) and displays a list of Articles in a block. The images (which is pulled from the underlying page) shows up in the Content Tree:

![image](https://user-images.githubusercontent.com/8974514/56533803-4221c380-650d-11e9-8be5-53cfeafb3f01.png)

An author can actually open up the dialogs for these images (from the content tree).

I think a quick fix in: `/apps/weretail/components/content/list/item.html` to explicitly add the `wcmmode=disabled` mode:

```diff
- <sly data-sly-resource="${item.path @ appendPath='/_jcr_content/root/hero_image', resourceType='weretail/components/content/image', decoration='false'}"></sly>
+ <sly data-sly-resource="${item.path @ wcmmode='disabled', appendPath='/_jcr_content/root/hero_image', resourceType='weretail/components/content/image', decoration='false'}"></sly>
```

**Comment by richardhand** [comment]
Closing this issue as development on We.Retail is discontinued. To be replaced by the [WKND Guide](https://github.com/adobe/aem-guides-wknd), as the future reference site for Adobe Experience Manager.
