### ISSUE TITLE
Site Search

### ISSUE THREAD

**Issue by dnlek** [Adobe-Marketing-Cloud/aem-sample-we-retail#31]
Publish-side search of:
- Products
- Content (e.g. experiences)
- Social Content (from Communities)
- People (from Communities)
- Popular searches

Need to find out whether we are able to use omnisearch (in-product solution) on publish instance.
We need to find out what is the API and how to do it properly.

**Comment by insideaem** [comment]
Hi Gabriel,
Any update on this issue?

Could you please point me to any existing API related to the omni search functionality?
Thanks,

**Comment by bpauli** [comment]
In 3.0.0 we integrated then new search component from the core-components
