### ISSUE TITLE
Remove the cqdam.pyramid.tiff rendition from assets

### ISSUE THREAD

**Issue by keepthebyte** [Adobe-Marketing-Cloud/aem-sample-we-retail#88]
They are generated on install of the package in the AEM instance. There is no need to ship them

that:
1. reduces the ZIP package size
2. speeds up install time

**Comment by justinedelson** [comment]
@keepthebyte I think this is already done, but please confirm.

**Comment by raducotescu** [comment]
I cannot find any more the asset @keepthebyte mentioned, therefore I'm closing this issue.
