### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by gargshivani111** [Adobe-Marketing-Cloud/aem-sample-we-retail#95]
Hi ,
  I am trying to build the project.But build has been failed and showing me error.

Failed to execute goal on project we.retail.core: Could not resolve dependencies for project we:we.retail.core:bundle:0.3.0-SNAPSHOT: The following artifacts could not be r
esolved: com.adobe.cq.commerce:cq-commerce-core:jar:5.14.84, com.adobe.cq.dam:cq-dam-cfm-api:jar:1.0.2, com.day.cq:cq-commons:jar:5.9.22: Failure to find com.adobe.cq.commerce:cq-c
ommerce-core:jar:5.14.84 in https://repo.adobe.com/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of a
dobe-public-releases has elapsed or updates are forced

**Comment by ankur-mittal** [comment]
I am facing the same issue. I resolved first one by changing cq-commerce-core jar version to 5.13.18 but cant seem to find cq-dam-cfm-api artifact in adobe nexus. Not sure how to fix that.

**Comment by gabrielwalt** [comment]
Thanks for the feedback, we'll look into it. Meanwhile, you can use the built package available in the releases section: https://github.com/Adobe-Marketing-Cloud/aem-sample-we-retail/releases
